version: '2'
services:
  web:
    build: .
    environment:
      REDIS_HOST: redis
      MONGO_HOST: mongo
      PORT: 5555
    ports:
      - 4000:5555
    links:
      - mongo
      - redis
  mongo:
    image: mongo:latest
  redis:
    image: redis:latest
